### ISSUE TITLE
Extension restart and disable commands

### ISSUE THREAD

**Issue by devnote-dev** [crystal-ameba/vscode-crystal-ameba#12]
Currently when there is an issue with the extension finding the Ameba executable (or after you've just installed Ameba as a dependency) the extension spams the notification bar with "... is not recognised" on Windows or "... ameba: not found" for Linux. Despite the path being later available in the desired location, the extension still complains and a window reload is required for the extension to work. It would be nice if there was a command which simply restarted the extension to do this.

There are also situations where the environment I'm working in doesn't use Ameba, to which the former issue arises again... A command to disable the extension in that workspace (or at least just turn it off) would be highly appreciated.

**Comment by veelenga** [comment]
That makes sense. However, I don't have too much capacity for this. If you would like to handle this, please be free to submit PR. If not, I will take a look later on.
