### ISSUE TITLE
Visual Studio Code open ameba issue on a separate window

### ISSUE THREAD

**Issue by Acciaiodigitale** [crystal-ameba/vscode-crystal-ameba#4]
For example if I write this simple code:

```
# TODO: Write documentation for `Web`
module Web
  require "kemal"

  VERSION = "0.1.0"

  get "/" do
    "Hello World!"
  end

  Kemal.run
end
```

It gives a:

```syntax error in 'STDIN:4:3': can't require inside type declarations```

on another windows on save only, so you have to undo the save and correct.

**Comment by veelenga** [comment]
Sorry, I didn’t understand what the issue is. There is a syntax error which needs to be corrected. Does ameba plugin somehow prevent you editing the file? Some screenshots could be useful

**Comment by Acciaiodigitale** [comment]
The syntax error, instead of showing contextually to the line, override the
file and become the first and only line of the file until you undo the save
action.

The if you ctrl-z (undo), you return to the originale file and can modify.
This Is dove of you have format on save option enabled.

Il ven 27 dic 2019, 17:47 Vitalii Elenhaupt <notifications@github.com> ha
scritto:

**Comment by veelenga** [comment]
I don't have any issues locally using the latest vscode plugin, crystal and ameba linter:

![image](https://user-images.githubusercontent.com/3624712/71528496-c7edde00-28e8-11ea-860d-fe488d138846.png)

It correctly shows me the error, the file can be saved and edited. 

Would be nice to have some screenshot/gif to better understand your issue.

**Comment by Acciaiodigitale** [comment]
1. Installed Crystal on Ubuntu (**Crystal v0.32.1**)
2. Installed Ameba from source (**Ameba v0.11.0**)
3. Created a project i(_crystal init app web_)
4. Open in VSCode (I have crystal-ameba and crystal-language extension by F. Aguilar)

If I have format on save option or try to format with CTRL + MAIUSC + I it screw like this:

![Uploading Schermata del 2019-12-28 08-21-37.png…]()

**Comment by Acciaiodigitale** [comment]
I try to disable your plugin and the problem went again. So probably the problem is with @faustinoaq plugin......what are you using for syntax higlight crystal?

**Comment by veelenga** [comment]
This plugins doesn’t do syntax highlighting, and does not format sources. 

@faustinoaq could you please take a look? This is probably related to “Crystal Language” extension.

**Comment by Acciaiodigitale** [comment]
@veelenga But in your screenshot I see syntax highlighting in crystal file: what are you using?
