### ISSUE TITLE
Extension fails with error "Could not execute Ameba file."

### ISSUE THREAD

**Issue by wJoenn** [crystal-ameba/vscode-crystal-ameba#88]
Hello 👋 
I wanted to install Ameba globally on my system but after doing so the extension is not able to execute the command anymore for some reason.

I've moved the `bin/ameba` executable inside my `$HOME/.asdf/plugins/crystal/bin` directory and added the directory to my `PATH` by writing `export PATH="$HOME/.asdf/plugins/crystal/bin:$PATH"` in my `.zshrc` config file.

When I run the command form a terminal everything works fine
```bash
➜  fullstack-challenges-crystal git:(master) ✗ ameba
Inspecting 11 files

..F........

00-Setup/00-Demo/src/demo.cr:4:3 [Correctable]
[C] Style/RedundantReturn: Redundant `return` detected
> return Math::PI * radius**2
  ^-------------------------^

Finished in 15.31 milliseconds
11 inspected, 1 failure
```

But I try to run the extension I have an error message that says
![image](https://github.com/crystal-ameba/vscode-crystal-ameba/assets/75388869/f8ca924e-34f6-4bd3-a3e1-49d370e3b419)

I've had a look at https://github.com/crystal-ameba/vscode-crystal-ameba/blob/master/src/configuration.ts and I don't see any reason it would be able to run the command.
I do not have a local `bin/ameba` file so the command should just be `ameba` which works when I run it as shown above.

Would you have any idea as to what the problem might be ?

**Comment by veelenga** [comment]
Can confirm the bug with the executable. 

Could you please extract the `onSave: true` question to a separate issue?

**Comment by wJoenn** [comment]
Done https://github.com/crystal-ameba/vscode-crystal-ameba/issues/89

**Comment by veelenga** [comment]
Hm, I double-checked this and can confirm that the global executable works well. You need to ensure that your VScode has the same environment as the one you have in the terminal. 

The code works correctly:

https://github.com/crystal-ameba/vscode-crystal-ameba/blob/9868b041fe473c1cf1e7cf2ed8c880a605aa1342/src/configuration.ts#L12-L17

It uses the global `ameba` executable by default and falls back to the local one if such is available in the workspace.

**Comment by veelenga** [comment]
Yes, I mean that the editor must use that setting you did in zsh: `export PATH="$HOME/.asdf/plugins/crystal/bin:$PATH"`. Could you please confirm that `ameba` binary works in the terminal that is running in VSCode?

**Comment by wJoenn** [comment]
Well I'm very confused but everything seems to be working now 🤔 (I was busy for the last couple of days and didn't have time to play around with Crystal so I didn't notice earlier)
```bash
➜  fullstack-challenges-crystal git:(master) ✗ which ameba
/home/joenn/.asdf/plugins/crystal/bin/ameba
➜  fullstack-challenges-crystal git:(master) ✗ ameba
Inspecting 46 files

.......................................F......

01-Crystal/01-Programming-basics/Optional-04-Valid-brackets/src/valid_brackets.cr:18:3 [Correctable]
[C] Style/RedundantReturn: Redundant `return` detected
> return stack.empty?
  ^-----------------^

Finished in 46.15 milliseconds
46 inspected, 1 failure
```
![image](https://github.com/crystal-ameba/vscode-crystal-ameba/assets/75388869/04e7231b-7b76-477c-a53d-c1e575adca07)

# 

Sorry for the false report 🙏 
Thanks for taking the time to try it on your end too
