### ISSUE TITLE
Add option to lint while typing instead of waiting for file save

### ISSUE THREAD

**Issue by wJoenn** [crystal-ameba/vscode-crystal-ameba#89]
While browsing through the [source code](https://github.com/crystal-ameba/vscode-crystal-ameba/blob/master/src/configuration.ts) I noticed that the `getConfig` method returns `onSave: true`.
Would it be possible to add a configuration so that we can change this settings to lint while writing the code instead of only checking after saving ?
Similar to `ruby-lsp`'s behaviour with Rubocop

https://github.com/crystal-ameba/vscode-crystal-ameba/assets/75388869/367909e5-ec16-4b94-a119-9f6f75ee0356

**Comment by nobodywasishere** [comment]
WIP implementation here. Won't be usable until after the next ameba release though.
https://github.com/nobodywasishere/vscode-crystal-ameba/tree/nobody/lint-on-type
